powercons<-read.table("household_power_consumption.txt",sep=";",header=T)
powerFeb<-powercons[which(powercons$Date=='1/2/2007' | powercons$Date=='2/2/2007'), ]
powerFeb<-transform(powerFeb, timestamp=as.POSIXct(strptime(paste(powerFeb$Date, powerFeb$Time),"%d/%m/%Y %H:%M:%S")))
powerFeb$Global_active_power<-as.numeric(as.character(powerFeb$Global_active_power))
powerFeb$Sub_metering_1<-as.numeric(as.character(powerFeb$Sub_metering_1))
powerFeb$Sub_metering_2<-as.numeric(as.character(powerFeb$Sub_metering_2))
powerFeb$Sub_metering_3<-as.numeric(as.character(powerFeb$Sub_metering_3))
powerFeb$Global_reactive_power<-as.numeric(as.character(powerFeb$Global_reactive_power))
powerFeb$Voltage<-as.numeric(as.character(powerFeb$Voltage))
png("plot4.png", width=480, height=480, units="px")
par(mfrow=c(2,2))
plot(powerFeb$timestamp,powerFeb$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(powerFeb$timestamp,powerFeb$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(powerFeb$timestamp,powerFeb$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(powerFeb$timestamp,powerFeb$Sub_metering_2,col="red")
lines(powerFeb$timestamp,powerFeb$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), bty="n", cex=.5)
plot(powerFeb$timestamp,powerFeb$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()